import { Button, Navbar, Text } from '@nextui-org/react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import Image from 'next/image';
import { useAccount, useNetwork } from 'wagmi';
import Index from '../components';
import styles from '../styles/Home.module.css';

export default function Home() {
  const { address, isConnected, status } = useAccount();
  const { chain: currentChain } = useNetwork();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar variant="floating">
          <Navbar.Brand>
            <Text b color="inherit" hideIn="xs">
              TaskRewards
            </Text>
          </Navbar.Brand>
          <Navbar.Content hideIn="xs" variant="highlight-solid-rounded">
            <Navbar.Link href="#">发起的项目</Navbar.Link>
            <Navbar.Link href="#">收到的项目</Navbar.Link>
            <Navbar.Link href="#">我的勋章</Navbar.Link>
          </Navbar.Content>
          <Navbar.Content>
            <ConnectButton />
          </Navbar.Content>
        </Navbar>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
