import Head from 'next/head';

export default function TaskHead() {
  return (
    <Head>
      <title>TaskRewards</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
